[tools]
air = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
"go:github.com/charmbracelet/freeze" = "latest"
"go:github.com/charmbracelet/sequin" = "latest"
gofumpt = "latest"
golangci-lint = "latest"
goreleaser = "latest"
gotestsum = "latest"
gum = "latest"
helix = "latest"
imagemagick = "latest"
jq = "latest"
node = "lts"
"npm:bash-language-server" = "latest"
"npm:esbuild" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
ripgrep = "latest"
rtk = "latest"
task = "latest"
tmux = "latest"
vhs = "latest"
yazi = "latest"
zellij = "latest"

[shell_alias]
p = "git pull && git cleanup && task -ls | grep -q install && task install"
t = "task"
y = "yazi"
z = "zellij"

[env]
DO_NOT_TRACK = "1"
EDITOR = "hx"
LESSCHARSET = "UTF-8"

_.path = [
  "~/.opencode/bin",
  "~/go/bin",
]
